name: Bump image tag on staging

on:
  repository_dispatch:
    types: [ "bump-image-tag-staging" ]

jobs:
  bump-image-tag-staging:
    name: Bump image tag on staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print received message body
        run: |
          echo "Received message body: ${{ toJSON(github.event.client_payload.message) }}"

      - name: Update chart image repo and tag
        uses: mikefarah/yq@v4.4.1
        with:
          cmd: |
            set -xe;
            yq e '.${{ github.event.client_payload.message.service_name }}.image.repository = "${{ github.event.client_payload.message.image_name }}"' -i settings/provisioning/${{ github.event.client_payload.message.service_name }}/values.yaml;
            yq e '.${{ github.event.client_payload.message.service_name }}.image.tag = "${{ github.event.client_payload.message.image_tag }}"' -i settings/provisioning/${{ github.event.client_payload.message.service_name }}/values.yaml;
            set +xe;

      - name: Configure Git
        run: |
          git config user.email "no-reply@cloud.ionos.com";
          git config user.name "IONOS GitHub Bot";

      - name: Commit image tag
        run: |
          set -xe;
          git status;
          git diff;
          git add settings/provisioning/${{ github.event.client_payload.message.service_name }}/values.yaml;
          git commit -m "Bump image tag for ${{ github.event.client_payload.message.service_name }} from ${{ github.event.client_payload.message.image_name }} to ${{ github.event.client_payload.message.image_tag }}";
          set +xe;

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: '[${{ github.event.client_payload.message.service_name }}] Update image tag'
          author: IONOS GitHub Bot <no-reply@cloud.ionos.com>
          commit-message: Update ${{ github.event.client_payload.message.service_name }} image tag ${{ github.event.client_payload.message.image_tag }}
          branch: ${{ github.event.client_payload.message.service_name }}_image_tag_${{ github.event.client_payload.message.image_tag }}
          delete-branch: true
          # token: "${{ github.event.client_payload.message.token }}"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Label PR
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          number: ${{ steps.cpr.outputs.pull-request-number }}"
          labels: |
            automated PR
            ${{ github.event.client_payload.message.service_name }}

  automerge-version-update:
    name: Automerge version update
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: APPROVE
          
      - name: automerge
        uses: pascalgn/automerge-action@v0.14.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "${{ github.event.client_payload.message.service_name }}"
          MERGE_METHOD: "squash"
